// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgBook struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Inventory            int32    `protobuf:"varint,2,opt,name=Inventory,proto3" json:"Inventory,omitempty"`
	Price                int32    `protobuf:"varint,3,opt,name=Price,proto3" json:"Price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgBook) Reset()         { *m = MsgBook{} }
func (m *MsgBook) String() string { return proto.CompactTextString(m) }
func (*MsgBook) ProtoMessage()    {}
func (*MsgBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{0}
}

func (m *MsgBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgBook.Unmarshal(m, b)
}
func (m *MsgBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgBook.Marshal(b, m, deterministic)
}
func (m *MsgBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBook.Merge(m, src)
}
func (m *MsgBook) XXX_Size() int {
	return xxx_messageInfo_MsgBook.Size(m)
}
func (m *MsgBook) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBook.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBook proto.InternalMessageInfo

func (m *MsgBook) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgBook) GetInventory() int32 {
	if m != nil {
		return m.Inventory
	}
	return 0
}

func (m *MsgBook) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type MessageQueryAllResponse struct {
	Head                 *MessageHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Books                []*MsgBook   `protobuf:"bytes,2,rep,name=Books,proto3" json:"Books,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MessageQueryAllResponse) Reset()         { *m = MessageQueryAllResponse{} }
func (m *MessageQueryAllResponse) String() string { return proto.CompactTextString(m) }
func (*MessageQueryAllResponse) ProtoMessage()    {}
func (*MessageQueryAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{1}
}

func (m *MessageQueryAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageQueryAllResponse.Unmarshal(m, b)
}
func (m *MessageQueryAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageQueryAllResponse.Marshal(b, m, deterministic)
}
func (m *MessageQueryAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageQueryAllResponse.Merge(m, src)
}
func (m *MessageQueryAllResponse) XXX_Size() int {
	return xxx_messageInfo_MessageQueryAllResponse.Size(m)
}
func (m *MessageQueryAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageQueryAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageQueryAllResponse proto.InternalMessageInfo

func (m *MessageQueryAllResponse) GetHead() *MessageHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *MessageQueryAllResponse) GetBooks() []*MsgBook {
	if m != nil {
		return m.Books
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgBook)(nil), "proto.MsgBook")
	proto.RegisterType((*MessageQueryAllResponse)(nil), "proto.MessageQueryAllResponse")
}

func init() { proto.RegisterFile("book.proto", fileDescriptor_1e89d0eaa98dc5d8) }

var fileDescriptor_1e89d0eaa98dc5d8 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xca, 0xcf, 0xcf,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x3c, 0xc9, 0xf9, 0xb9, 0xb9,
	0xf9, 0x79, 0x10, 0x41, 0xa5, 0x40, 0x2e, 0x76, 0xdf, 0xe2, 0x74, 0xa7, 0xfc, 0xfc, 0x6c, 0x21,
	0x21, 0x2e, 0x16, 0xbf, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b,
	0x48, 0x86, 0x8b, 0xd3, 0x33, 0xaf, 0x2c, 0x35, 0xaf, 0x24, 0xbf, 0xa8, 0x52, 0x82, 0x49, 0x81,
	0x51, 0x83, 0x35, 0x08, 0x21, 0x20, 0x24, 0xc2, 0xc5, 0x1a, 0x50, 0x94, 0x99, 0x9c, 0x2a, 0xc1,
	0x0c, 0x96, 0x81, 0x70, 0x94, 0xd2, 0xb9, 0xc4, 0x7d, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x03,
	0x4b, 0x53, 0x8b, 0x2a, 0x1d, 0x73, 0x72, 0x82, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85,
	0xd4, 0xb8, 0x58, 0x3c, 0x52, 0x13, 0x53, 0xc0, 0x56, 0x70, 0x1b, 0x09, 0x41, 0xdc, 0xa0, 0x07,
	0x55, 0x0d, 0x92, 0x09, 0x02, 0xcb, 0x0b, 0xa9, 0x70, 0xb1, 0x82, 0x9c, 0x54, 0x2c, 0xc1, 0xa4,
	0xc0, 0xac, 0xc1, 0x6d, 0xc4, 0x07, 0x53, 0x08, 0x71, 0x69, 0x10, 0x44, 0x32, 0x89, 0x0d, 0x2c,
	0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x4c, 0x11, 0x65, 0xe5, 0x00, 0x00, 0x00,
}
