// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mgr.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageModifyBookRequest struct {
	Head                 *MessageHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Book                 *MsgBook     `protobuf:"bytes,2,opt,name=Book,proto3" json:"Book,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MessageModifyBookRequest) Reset()         { *m = MessageModifyBookRequest{} }
func (m *MessageModifyBookRequest) String() string { return proto.CompactTextString(m) }
func (*MessageModifyBookRequest) ProtoMessage()    {}
func (*MessageModifyBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b589f75408ae08b4, []int{0}
}

func (m *MessageModifyBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageModifyBookRequest.Unmarshal(m, b)
}
func (m *MessageModifyBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageModifyBookRequest.Marshal(b, m, deterministic)
}
func (m *MessageModifyBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageModifyBookRequest.Merge(m, src)
}
func (m *MessageModifyBookRequest) XXX_Size() int {
	return xxx_messageInfo_MessageModifyBookRequest.Size(m)
}
func (m *MessageModifyBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageModifyBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageModifyBookRequest proto.InternalMessageInfo

func (m *MessageModifyBookRequest) GetHead() *MessageHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *MessageModifyBookRequest) GetBook() *MsgBook {
	if m != nil {
		return m.Book
	}
	return nil
}

type MessageEnterNewRequest struct {
	Head                 *MessageHead `protobuf:"bytes,1,opt,name=Head,proto3" json:"Head,omitempty"`
	Books                []*MsgBook   `protobuf:"bytes,2,rep,name=Books,proto3" json:"Books,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MessageEnterNewRequest) Reset()         { *m = MessageEnterNewRequest{} }
func (m *MessageEnterNewRequest) String() string { return proto.CompactTextString(m) }
func (*MessageEnterNewRequest) ProtoMessage()    {}
func (*MessageEnterNewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b589f75408ae08b4, []int{1}
}

func (m *MessageEnterNewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageEnterNewRequest.Unmarshal(m, b)
}
func (m *MessageEnterNewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageEnterNewRequest.Marshal(b, m, deterministic)
}
func (m *MessageEnterNewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageEnterNewRequest.Merge(m, src)
}
func (m *MessageEnterNewRequest) XXX_Size() int {
	return xxx_messageInfo_MessageEnterNewRequest.Size(m)
}
func (m *MessageEnterNewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageEnterNewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageEnterNewRequest proto.InternalMessageInfo

func (m *MessageEnterNewRequest) GetHead() *MessageHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *MessageEnterNewRequest) GetBooks() []*MsgBook {
	if m != nil {
		return m.Books
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageModifyBookRequest)(nil), "proto.MessageModifyBookRequest")
	proto.RegisterType((*MessageEnterNewRequest)(nil), "proto.MessageEnterNewRequest")
}

func init() { proto.RegisterFile("mgr.proto", fileDescriptor_b589f75408ae08b4) }

var fileDescriptor_b589f75408ae08b4 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x4d, 0x2f, 0xd2,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x3c, 0xc9, 0xf9, 0xb9, 0xb9, 0xf9,
	0x79, 0x10, 0x41, 0x29, 0xae, 0xa4, 0xfc, 0xfc, 0x6c, 0x08, 0x5b, 0x29, 0x8d, 0x4b, 0xc2, 0x37,
	0xb5, 0xb8, 0x38, 0x31, 0x3d, 0xd5, 0x37, 0x3f, 0x25, 0x33, 0xad, 0xd2, 0x29, 0x3f, 0x3f, 0x3b,
	0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x8d, 0x8b, 0xc5, 0x23, 0x35, 0x31, 0x45, 0x82,
	0x51, 0x81, 0x51, 0x83, 0xdb, 0x48, 0x08, 0xa2, 0x43, 0x0f, 0xaa, 0x1c, 0x24, 0x13, 0x04, 0x96,
	0x17, 0x52, 0xe2, 0x62, 0x01, 0x69, 0x93, 0x60, 0x02, 0xab, 0xe3, 0x83, 0xa9, 0x2b, 0x4e, 0x07,
	0x1b, 0x06, 0x96, 0x53, 0x4a, 0xe3, 0x12, 0x83, 0x6a, 0x74, 0xcd, 0x2b, 0x49, 0x2d, 0xf2, 0x4b,
	0x2d, 0x27, 0xd5, 0x16, 0x15, 0x2e, 0x56, 0x90, 0x49, 0xc5, 0x12, 0x4c, 0x0a, 0xcc, 0x58, 0xac,
	0x81, 0x48, 0x1a, 0x9d, 0x64, 0xe4, 0x62, 0x07, 0xb1, 0x7c, 0xd3, 0x8b, 0x84, 0x6c, 0xb9, 0x58,
	0x03, 0x4b, 0x53, 0x8b, 0x2a, 0x85, 0xb0, 0x18, 0x2a, 0x25, 0x87, 0x2a, 0x06, 0x56, 0xe8, 0x98,
	0x93, 0x13, 0x94, 0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0xaa, 0xc4, 0x20, 0x64, 0xc5, 0xc5, 0x85,
	0x08, 0x13, 0xac, 0x66, 0x88, 0xa1, 0x8a, 0x21, 0xe9, 0x75, 0xe6, 0xe2, 0x80, 0xf9, 0x53, 0x48,
	0x16, 0x55, 0x15, 0x9a, 0xff, 0x71, 0x1b, 0x92, 0xc4, 0x06, 0x96, 0x30, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xf2, 0xca, 0xe3, 0x61, 0xd0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookMgrClient is the client API for BookMgr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookMgrClient interface {
	Query(ctx context.Context, in *MessageHead, opts ...grpc.CallOption) (*MessageQueryAllResponse, error)
	ModifyBook(ctx context.Context, in *MessageHead, opts ...grpc.CallOption) (*MessageResponse, error)
	EnterNew(ctx context.Context, in *MessageEnterNewRequest, opts ...grpc.CallOption) (*MessageResponse, error)
}

type bookMgrClient struct {
	cc *grpc.ClientConn
}

func NewBookMgrClient(cc *grpc.ClientConn) BookMgrClient {
	return &bookMgrClient{cc}
}

func (c *bookMgrClient) Query(ctx context.Context, in *MessageHead, opts ...grpc.CallOption) (*MessageQueryAllResponse, error) {
	out := new(MessageQueryAllResponse)
	err := c.cc.Invoke(ctx, "/proto.BookMgr/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookMgrClient) ModifyBook(ctx context.Context, in *MessageHead, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/proto.BookMgr/ModifyBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookMgrClient) EnterNew(ctx context.Context, in *MessageEnterNewRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/proto.BookMgr/EnterNew", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookMgrServer is the server API for BookMgr service.
type BookMgrServer interface {
	Query(context.Context, *MessageHead) (*MessageQueryAllResponse, error)
	ModifyBook(context.Context, *MessageHead) (*MessageResponse, error)
	EnterNew(context.Context, *MessageEnterNewRequest) (*MessageResponse, error)
}

// UnimplementedBookMgrServer can be embedded to have forward compatible implementations.
type UnimplementedBookMgrServer struct {
}

func (*UnimplementedBookMgrServer) Query(ctx context.Context, req *MessageHead) (*MessageQueryAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (*UnimplementedBookMgrServer) ModifyBook(ctx context.Context, req *MessageHead) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyBook not implemented")
}
func (*UnimplementedBookMgrServer) EnterNew(ctx context.Context, req *MessageEnterNewRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnterNew not implemented")
}

func RegisterBookMgrServer(s *grpc.Server, srv BookMgrServer) {
	s.RegisterService(&_BookMgr_serviceDesc, srv)
}

func _BookMgr_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageHead)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookMgrServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BookMgr/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookMgrServer).Query(ctx, req.(*MessageHead))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookMgr_ModifyBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageHead)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookMgrServer).ModifyBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BookMgr/ModifyBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookMgrServer).ModifyBook(ctx, req.(*MessageHead))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookMgr_EnterNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageEnterNewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookMgrServer).EnterNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BookMgr/EnterNew",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookMgrServer).EnterNew(ctx, req.(*MessageEnterNewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookMgr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BookMgr",
	HandlerType: (*BookMgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _BookMgr_Query_Handler,
		},
		{
			MethodName: "ModifyBook",
			Handler:    _BookMgr_ModifyBook_Handler,
		},
		{
			MethodName: "EnterNew",
			Handler:    _BookMgr_EnterNew_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mgr.proto",
}
